import { WrenchScrewdriverIcon } from '@heroicons/react/24/solid'
import Head from 'next/head'
import Navigation from '../../components/navigation'

export default function PlayerHome() {
  return (
    <>
      <Head>
        {/* TODO: change title? */}
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* This Navigation component creates links to other tabs, such as the tournaments or chapters tag. */}
      <Navigation tab="chapter" />

      {/* This portion of the website is under construction. */}
      <div className="grid place-items-center justify-center align-middle mt-16">
        <div className='justify-center'>
          <WrenchScrewdriverIcon className='h-24 w-24' />
          <h1 className='font-bold text-4xl '>This portion of the website is currently under construction.</h1>
          <h1 className='text-xl'>Planned Content: Start a chapter, manage rosters, sign team up for tournaments.</h1>
        </div>
      </div>
    </>
  )
}
